using UnityEngine;
using UnityEngine.XR;
using System.Collections.Generic;
using System.IO;

/// Manages the main experiment scene for the Muscle Memory Acquisition study.
///
/// Handles the full experiment lifecycle:
///   WaitingToStart — participant aims at the Begin button and clicks it.
///   Countdown      — a 3-second countdown displays before timing begins.
///   Running        — participant draws the dot pattern; attempts are checked
///                    and logged as correct or incorrect.
///   Complete       — triggered after 3 correct attempts; results are saved
///                    to a CSV file and the display shows a summary.
///
/// Data is written to a local CSV file (csvPath) with one row per session,
/// recording the date, time, total elapsed time, and attempt counts.

public class DrawingManager : MonoBehaviour
{
    // ── Inspector References ───────────────────────────────────────────────

    [Header("References")]
    // The Transform of the right-hand VR controller, used to cast the aim ray
    public Transform controllerTransform;
    // Material applied to all drawn lines between dots
    public Material lineMaterial;
    // Uniform width of each drawn line in world units
    public float lineWidth = 0.05f;
    // TextMesh that displays the countdown and elapsed time during the experiment
    public TextMesh timerDisplay;
    // TextMesh that displays correct/incorrect attempt counts and the final summary
    public TextMesh statsDisplay;
    // The "Begin" button GameObject — hidden once the experiment starts
    public GameObject beginButton;

    // ── Dot Drawing State ──────────────────────────────────────────────────

    // The dot currently selected (held) by the participant
    private GameObject currentDot = null;
    // The dot currently being aimed at by the controller ray
    private GameObject hoveredDot = null;
    // All LineRenderer objects drawn in the current attempt
    private List<LineRenderer> drawnLines = new List<LineRenderer>();
    // Ordered list of dots visited in the current attempt, used for pattern checking
    private List<GameObject> visitedDots = new List<GameObject>();
    // Prevents repeated trigger actions from a single button hold
    private bool isTriggerHeld = false;
    // The temporary line shown from the controller tip while aiming
    private LineRenderer previewLine;
    // The detected right-hand XR input device
    private InputDevice rightDevice;

    // ── Reset State ────────────────────────────────────────────────────────

    // True while waiting for the brief reset pause between attempts
    private bool isResetting = false;
    // Countdown timer for the reset pause (seconds)
    private float resetTimer = 0f;

    // ── Experiment State Machine ───────────────────────────────────────────

    // The four states the experiment can be in
    private enum ExperimentState { WaitingToStart, Countdown, Running, Complete }
    // Current state of the experiment
    private ExperimentState state = ExperimentState.WaitingToStart;
    // Countdown timer that counts down from 3 before the experiment begins
    private float countdownTimer = 3f;
    // Time.time value recorded when the experiment started, used to compute elapsed time
    private float experimentStartTime = 0f;
    // Number of correctly completed pattern attempts so far
    private int correctCount = 0;
    // Number of incorrectly completed pattern attempts so far
    private int incorrectCount = 0;
    // Total elapsed time when the experiment completes (saved to CSV)
    private float totalTime = 0f;

    // ── Data Logging ───────────────────────────────────────────────────────

    // Absolute path to the CSV file where experiment results are saved
    private string csvPath = @"C:\Users\RLNel\Documents\Spring2026\SP26-Tactile-VR\prototype\Assets\scripts\Data.csv";

    // ── Correct Pattern Definition ─────────────────────────────────────────

    // The exact sequence of dot names the participant must visit, in order,
    // to register a correct attempt. Dot names correspond to Dot_row_col
    // as generated by DotGrid.cs.
    private string[] correctPattern = new string[]
    {
        "Dot_2_0", "Dot_2_1", "Dot_2_2", "Dot_1_1", "Dot_0_0",
        "Dot_0_1", "Dot_0_2", "Dot_1_0", "Dot_1_1", "Dot_1_2"
    };

    // ── Start ──────────────────────────────────────────────────────────────
    void Start()
    {
        // Create the preview line shown from the controller tip while aiming
        GameObject previewObj = new GameObject("PreviewLine");
        previewLine = previewObj.AddComponent<LineRenderer>();

        // Give the preview line a distinct pink color so it doesn't look
        // like a completed drawn line
        Material previewMat = new Material(lineMaterial);
        previewMat.color = new Color(1f, 0.4f, 0.7f);

        previewLine.material = previewMat;
        previewLine.startColor = new Color(1f, 0.4f, 0.7f);
        previewLine.endColor = new Color(1f, 0.4f, 0.7f);
        previewLine.widthCurve = new AnimationCurve(
            new Keyframe(0, 0.02f),
            new Keyframe(1, 0.02f)
        );
        previewLine.widthMultiplier = 1f;
        previewLine.positionCount = 2;
        previewLine.useWorldSpace = true;
        previewLine.enabled = true;

        // Create the CSV file with column headers if it doesn't already exist
        if (!File.Exists(csvPath))
        {
            File.WriteAllText(csvPath, "Date,Time,TotalTime,Correct,Incorrect\n");
            Debug.Log("Created new CSV at: " + csvPath);
        }

        // Clear the timer and stats displays on startup
        UpdateTimerDisplay("", 50);
        UpdateStatsDisplay("");

        // Attempt to find the right-hand controller device
        TryGetDevice();
    }


    /// Attempts to find and cache the right-hand VR controller device.
    /// Called once at Start and again each frame if the device is not yet valid.

    void TryGetDevice()
    {
        var devices = new List<InputDevice>();
        InputDevices.GetDevicesWithCharacteristics(
            InputDeviceCharacteristics.Right |
            InputDeviceCharacteristics.Controller, devices);

        if (devices.Count > 0)
        {
            rightDevice = devices[0];
            Debug.Log("Got device: " + rightDevice.name);
        }
    }


    /// Called by the Begin button to start the 3-second countdown.
    /// Transitions state to Countdown and resets the countdown timer.

    public void StartExperiment()
    {
        state = ExperimentState.Countdown;
        countdownTimer = 3f;
        UpdateTimerDisplay("3", 80);
    }

    // ── Update ─────────────────────────────────────────────────────────────
    void Update()
    {
        // If the controller hasn't been detected yet, keep trying
        if (!rightDevice.isValid)
        {
            TryGetDevice();
            return;
        }

        // Update the preview line every frame so it always extends from the
        // controller tip in the direction the participant is pointing
        previewLine.SetPosition(0, controllerTransform.position);
        previewLine.SetPosition(1, controllerTransform.position + controllerTransform.forward * 5f);

        // Read the trigger axis — treated as pressed if over 50% depressed
        float triggerValue = 0f;
        rightDevice.TryGetFeatureValue(CommonUsages.trigger, out triggerValue);
        bool triggerPressed = triggerValue > 0.5f;

        // Delegate to the handler for the current experiment state
        switch (state)
        {
            case ExperimentState.WaitingToStart:
                HandleButtonRaycast(triggerPressed);
                break;

            case ExperimentState.Countdown:
                HandleCountdown();
                break;

            case ExperimentState.Running:
                HandleRunning(triggerPressed);
                break;

            case ExperimentState.Complete:
                // Nothing to update — experiment is finished
                break;
        }
    }

    // ── WaitingToStart ─────────────────────────────────────────────────────

    /// Waits for the participant to aim at and click the Begin button.
    /// Hides the button and calls StartExperiment() on a valid click.

    void HandleButtonRaycast(bool triggerPressed)
    {
        Ray ray = new Ray(controllerTransform.position, controllerTransform.forward);
        RaycastHit hit;

        if (Physics.Raycast(ray, out hit, 10f))
        {
            if (hit.collider.gameObject.name == "BeginButton" && triggerPressed && !isTriggerHeld)
            {
                isTriggerHeld = true;
                beginButton.SetActive(false); // Hide the button so it can't be clicked again
                StartExperiment();
            }
        }

        // Clear the held flag once the trigger is released
        if (!triggerPressed) isTriggerHeld = false;
    }

    // ── Countdown ──────────────────────────────────────────────────────────

    /// Counts down from 3 and displays each second on the timer display.
    /// When the countdown reaches zero, transitions to the Running state
    /// and records the experiment start time.
 
    void HandleCountdown()
    {
        countdownTimer -= Time.deltaTime;

        // Display the appropriate countdown number based on remaining time
        if (countdownTimer > 2f)
            UpdateTimerDisplay("3", 80);
        else if (countdownTimer > 1f)
            UpdateTimerDisplay("2", 80);
        else if (countdownTimer > 0f)
            UpdateTimerDisplay("1", 80);
        else
        {
            // Countdown finished — start the experiment
            UpdateTimerDisplay("GO!", 80);
            state = ExperimentState.Running;
            experimentStartTime = Time.time;
        }
    }

    // ── Running ────────────────────────────────────────────────────────────

    /// Main experiment loop. Updates the elapsed time display, handles
    /// dot hover highlighting, and processes trigger input to select dots
    /// and draw lines. Calls CheckPattern() when the trigger is released.
    
    void HandleRunning(bool triggerPressed)
    {
        float elapsed = Time.time - experimentStartTime;

        // Update the live timer and attempt counts (skip during the reset pause)
        if (!isResetting)
        {
            UpdateTimerDisplay(elapsed.ToString("F1") + "s", 60);
            UpdateStatsDisplay(
                "Correct:   " + correctCount + "\n" +
                "Incorrect: " + incorrectCount
            );
        }

        // Handle the brief pause between attempts before clearing the board
        if (isResetting)
        {
            resetTimer -= Time.deltaTime;
            if (resetTimer <= 0f)
            {
                isResetting = false;
                ResetPattern(); // Clear lines and dot colors for the next attempt
            }
            return; // Skip input handling during the reset pause
        }

        // Update dot hover highlight based on where the controller is pointing
        HandleHover();

        if (triggerPressed)
        {
            if (!isTriggerHeld)
            {
                // Fresh trigger press — try to select a start dot
                isTriggerHeld = true;
                TrySelectStartDot();
            }
            else
            {
                // Trigger held and dragging — if the ray moves to a new dot,
                // draw a line from the current dot to it and advance selection
                if (currentDot != null && hoveredDot != null && hoveredDot != currentDot)
                {
                    DrawLine(currentDot.transform.position, hoveredDot.transform.position);
                    SetDotColor(currentDot, Color.green); // Mark the left dot as completed
                    currentDot = hoveredDot;              // Advance to the newly connected dot
                    visitedDots.Add(currentDot);
                    SetDotColor(currentDot, Color.yellow); // Highlight the new current dot
                }
            }
        }
        else
        {
            // Trigger released — finalize the attempt and check the pattern
            if (isTriggerHeld)
            {
                isTriggerHeld = false;
                if (currentDot != null)
                {
                    SetDotColor(currentDot, Color.yellow);
                    currentDot = null;
                }
                CheckPattern();
            }
        }

        // While the trigger is held, update the preview line endpoint
        // to snap to the hovered dot or extend freely toward the controller forward
        if (isTriggerHeld && currentDot != null)
        {
            previewLine.SetPosition(0, controllerTransform.position);
            if (hoveredDot != null && hoveredDot != currentDot)
                previewLine.SetPosition(1, hoveredDot.transform.position);
            else
                previewLine.SetPosition(1, controllerTransform.position + controllerTransform.forward * 5f);
        }
    }

    // ── Pattern Checking ───────────────────────────────────────────────────

    /// Compares the sequence of dots visited in the current attempt against
    /// the correct pattern. Flashes dots and lines green for a correct attempt
    /// or red for an incorrect one. Increments the appropriate counter and
    /// triggers a reset. Ends the experiment after 3 correct attempts.

    void CheckPattern()
    {
        // Nothing to check if the participant didn't touch any dots
        if (visitedDots.Count == 0) return;

        bool correct = false;

        // The attempt is only correct if the visited dot count matches exactly
        // and every dot name matches the expected pattern in order
        if (visitedDots.Count == correctPattern.Length)
        {
            correct = true;
            for (int i = 0; i < correctPattern.Length; i++)
            {
                if (visitedDots[i].name != correctPattern[i])
                {
                    correct = false;
                    break;
                }
            }
        }

        // Flash all visited dots and drawn lines green (correct) or red (incorrect)
        Color flashColor = correct ? Color.green : Color.red;

        foreach (GameObject dot in visitedDots)
            SetDotColor(dot, flashColor);
        foreach (LineRenderer lr in drawnLines)
        {
            lr.startColor = flashColor;
            lr.endColor = flashColor;
        }

        if (correct)
        {
            correctCount++;
            Debug.Log("Correct! " + correctCount + "/3");

            // After 3 correct attempts, end the experiment and save results
            if (correctCount >= 3)
            {
                totalTime = Time.time - experimentStartTime;
                state = ExperimentState.Complete;
                UpdateTimerDisplay("Done!", 60);
                UpdateStatsDisplay(
                    "Complete!\n" +
                    "Total time: " + totalTime.ToString("F2") + "s\n" +
                    "Correct:    " + correctCount + "\n" +
                    "Incorrect:  " + incorrectCount
                );
                SaveToCSV();
                // Brief pause before the final reset so the participant can see the green flash
                isResetting = true;
                resetTimer = 0.5f;
                return;
            }
        }
        else
        {
            incorrectCount++;
            Debug.Log("Incorrect! " + incorrectCount + " mistakes so far.");
        }

        // Start the reset pause before clearing the board for the next attempt
        isResetting = true;
        resetTimer = 0.5f;
    }

    // ── CSV Logging ────────────────────────────────────────────────────────

    /// Appends a single row of experiment results to the CSV file.
    /// Creates the file with headers if it doesn't exist.
    /// Each row contains: date, time, total time, correct count, incorrect count.
   
    void SaveToCSV()
    {
        try
        {
            // Recreate the file with headers if it was deleted since Start()
            if (!File.Exists(csvPath))
            {
                string header = "Date,Time (HH:MM:SS),Total Time (s),Successful Attempts,Missed Attempts\n";
                File.WriteAllText(csvPath, header);
            }

            string date = System.DateTime.Now.ToString("yyyy-MM-dd");
            string time = System.DateTime.Now.ToString("HH:mm:ss");
            string newLine = date + "," + time + "," + totalTime.ToString("F2") + "," + correctCount + "," + incorrectCount + "\n";
            File.AppendAllText(csvPath, newLine);
            Debug.Log("Data saved to CSV: " + newLine);
        }
        catch (System.Exception e)
        {
            Debug.LogError("Failed to save CSV: " + e.Message);
        }
    }

    // ── Pattern Reset ──────────────────────────────────────────────────────
    
    /// Destroys all drawn lines, resets dot colors to black, and clears
    /// the visited dot list so the participant can start a fresh attempt.
  
    void ResetPattern()
    {
        foreach (LineRenderer lr in drawnLines)
            Destroy(lr.gameObject);
        drawnLines.Clear();

        foreach (GameObject dot in visitedDots)
            SetDotColor(dot, Color.black);
        visitedDots.Clear();

        currentDot = null;
        hoveredDot = null;
    }

    // ── Hover Highlighting ─────────────────────────────────────────────────
  
    /// Casts a ray from the controller and highlights any dot it hits in red.
    /// Restores the previous hovered dot to black when the ray moves away,
    /// unless that dot is the currently selected dot.

    void HandleHover()
    {
        Ray ray = new Ray(controllerTransform.position, controllerTransform.forward);
        RaycastHit hit;
        GameObject newHover = null;

        if (Physics.Raycast(ray, out hit, 10f))
        {
            // Only highlight objects whose names start with "Dot_"
            if (hit.collider.gameObject.name.StartsWith("Dot_"))
                newHover = hit.collider.gameObject;
        }

        // Only update colors if the hovered dot has changed this frame
        if (newHover != hoveredDot)
        {
            // Restore the previously hovered dot to black (unless it's the selected dot)
            if (hoveredDot != null && hoveredDot != currentDot)
                SetDotColor(hoveredDot, Color.black);
            // Highlight the newly hovered dot red (unless it's the selected dot)
            if (newHover != null && newHover != currentDot)
                SetDotColor(newHover, Color.red);
            hoveredDot = newHover;
        }
    }

    // ── Dot Selection ──────────────────────────────────────────────────────

    /// Casts a ray from the controller on a fresh trigger press.
    /// If a dot is hit, selects it as the starting dot for the current attempt.

    void TrySelectStartDot()
    {
        Ray ray = new Ray(controllerTransform.position, controllerTransform.forward);
        RaycastHit hit;

        if (Physics.Raycast(ray, out hit, 10f))
        {
            if (hit.collider.gameObject.name.StartsWith("Dot_"))
            {
                currentDot = hit.collider.gameObject;
                visitedDots.Add(currentDot);
                SetDotColor(currentDot, Color.yellow); // Yellow indicates the currently selected dot
            }
        }
    }

    // ── Line Drawing ───────────────────────────────────────────────────────
  
    /// Creates a new LineRenderer between two world-space positions and
    /// adds it to the drawnLines list so it can be cleared on reset.
    void DrawLine(Vector3 start, Vector3 end)
    {
        GameObject lineObj = new GameObject("Line");
        LineRenderer lr = lineObj.AddComponent<LineRenderer>();
        lr.material = lineMaterial;
        lr.widthCurve = new AnimationCurve(
            new Keyframe(0, 0.05f),
            new Keyframe(1, 0.05f)
        );
        lr.widthMultiplier = 1f;
        lr.startWidth = 0.05f;
        lr.endWidth = 0.05f;
        lr.startColor = Color.black;
        lr.endColor = Color.black;
        lr.positionCount = 2;
        lr.SetPosition(0, start);
        lr.SetPosition(1, end);
        lr.useWorldSpace = true;
        drawnLines.Add(lr);
    }

    // ── Utility Helpers ────────────────────────────────────────────────────

 
    /// Sets the color of a dot's material directly.
    /// Note: this modifies the material instance on the renderer, so each
    /// dot should have its own material to avoid unintended shared changes.
       void SetDotColor(GameObject dot, Color color)
    {
        Renderer r = dot.GetComponent<Renderer>();
        if (r != null)
            r.material.color = color;
    }

 
    /// Updates the timer TextMesh with the given text and font size,
    /// and logs the value to the Unity console.
  
    void UpdateTimerDisplay(string text, int fontSize)
    {
        if (timerDisplay != null)
        {
            timerDisplay.text = text;
            timerDisplay.fontSize = fontSize;
        }
        Debug.Log("[Timer] " + text);
    }


    /// Updates the stats TextMesh with the given text and logs it to the console.

    void UpdateStatsDisplay(string text)
    {
        if (statsDisplay != null)
            statsDisplay.text = text;
        Debug.Log("[Stats] " + text);
    }


    /// Public method to clear all drawn lines and reset dot colors.
    /// Can be called externally ( from a UI button) if needed.

    public void ClearLines()
    {
        ResetPattern();
    }
}